name: Gradle build

on:
  push:
    branches: [ dev, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-java@v3.0.0
        with:
          java-version: 11
          distribution: liberica
      - uses: gradle/gradle-build-action@v2.1.5
        with:
          arguments: build
